hotkeys:
  shell: {}
  toggle-fullscreen:
    - - Ctrl-Enter
  toggle-window: []
  profile: {}
  close-pane:
    - - Alt-Shift-W
  split-right:
    - - Ctrl-Shift-Right
  split-bottom:
    - - Ctrl-Shift-Down
  split-left:
    - - Ctrl-Shift-Left
  split-top:
    - - Ctrl-Shift-Up
  pane-nav-up:
    - - Alt-ArrowUp
  pane-nav-down:
    - - Alt-ArrowDown
  pane-nav-left:
    - - Alt-ArrowLeft
  pane-nav-right:
    - - Alt-ArrowRight
  next-tab:
    - - Ctrl-Tab
  previous-tab:
    - - Ctrl-Shift-Tab
terminal:
  colorScheme: &ref_0
    name: Nord
    foreground: '#D8DEE9'
    background: '#2E3440'
    cursor: '#'
    colors:
      - '#3B4252'
      - '#BF616A'
      - '#A3BE8C'
      - '#EBCB8B'
      - '#81A1C1'
      - '#B48EAD'
      - '#88C0D0'
      - '#E5E9F0'
      - '#4C566A'
      - '#BF616A'
      - '#A3BE8C'
      - '#EBCB8B'
      - '#81A1C1'
      - '#B48EAD'
      - '#8FBCBB'
      - '#ECEFF4'
  autoOpen: true
  environment: {}
  shell: powershell
  workingDirectory: 'C:\git'
  font: Dank Mono
  frontend: xterm-webgl
  ligatures: true
  background: colorScheme
  cursor: block
  rightClick: paste
  bell: visual
  customColorSchemes:
    - *ref_0
  fontSize: 13
  copyOnSelect: true
  profile: powershell
appearance:
  theme: Standard
  vibrancy: true
  vibrancyType: fluent
  opacity: 0.99
  frame: thin
  dock: 'off'
  dockFill: 1
  tabsLocation: top
  css: '/* * { color: blue !important; } */'
enableAnalytics: false
titleControl:
  replacePattern: \cmd
  removePattern: 'Administrator:'
enableWelcomeTab: false
pluginBlacklist:
  - shell-selector
enableAutomaticUpdates: true
